version: "3"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-desafio-indique-amigo
    entrypoint: docker/entrypoint.sh
    tty: true
    volumes:
      - .:/var/www/html
    ports:
      - "9000"
    networks:
      - default

  nginx:
    image: nginx:stable-alpine
    container_name: nginx-desafio-indique-amigo
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - default
    depends_on:
      - app

  db:
    image: postgres
    restart: always
    ports:
    - "54321:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: desafio_indicacao
      PGDATA: pg-volume:/var/lib/postgresql/data/pgdata
    volumes: 
      - ./data/sql/:/docker-entrypoint-initdb.d/

volumes:
  pg-volume: